return {
  {
    "catppuccin/nvim",
    name = "catppuccin",
    lazy = false,
    priority = 1000,
    opts = {
      background = {
        light = "latte",
        dark = "macchiato",
      },
      color_overrides = {
        latte = {
          rosewater = "#cc7983",
          flamingo = "#bb5d60",
          pink = "#d54597",
          mauve = "#a65fd5",
          red = "#b7242f",
          maroon = "#db3e68",
          peach = "#e46f2a",
          yellow = "#bc8705",
          green = "#1a8e32",
          teal = "#00a390",
          sky = "#089ec0",
          sapphire = "#0ea0a0",
          blue = "#017bca",
          lavender = "#8584f7",
          text = "#444444",
          subtext1 = "#555555",
          subtext0 = "#666666",
          overlay2 = "#777777",
          overlay1 = "#888888",
          overlay0 = "#999999",
          surface2 = "#aaaaaa",
          surface1 = "#bbbbbb",
          surface0 = "#cccccc",
          base = "#ffffff",
          mantle = "#eeeeee",
          crust = "#dddddd",
        },
        frappe = {
          rosewater = "#efc9c2",
          flamingo = "#ebb2b2",
          pink = "#f2a7de",
          mauve = "#b889f4",
          red = "#ea7183",
          maroon = "#ea838c",
          peach = "#f39967",
          yellow = "#eaca89",
          green = "#96d382",
          teal = "#78cec1",
          sky = "#91d7e3",
          sapphire = "#68bae0",
          blue = "#739df2",
          lavender = "#a0a8f6",
          text = "#b5c1f1",
          subtext1 = "#a6b0d8",
          subtext0 = "#959ec2",
          overlay2 = "#848cad",
          overlay1 = "#717997",
          overlay0 = "#63677f",
          surface2 = "#505469",
          surface1 = "#3e4255",
          surface0 = "#2c2f40",
          base = "#1a1c2a",
          mantle = "#141620",
          crust = "#0e0f16",
        },
      },
      integrations = {
        nvim_surround = true,
      },
    },
    config = function(_, opts)
      require("catppuccin").setup(opts)
      vim.cmd [[colorscheme catppuccin]]
    end,
  },
  {
    "nvim-tree/nvim-web-devicons",
    lazy = true,
    opts = {
      cer = { icon = "󱆆", color = "#ebcb8b", name = "cer" },
      css = { icon = "", color = "#61afef", name = "css" },
      cnf = { icon = "󱙌", color = "#898998", name = "cnf" },
      db = { icon = "󱘲", color = "#ff75a0", name = "db" },
      html = { icon = "", color = "#de8c92", name = "html" },
      js = { icon = "", color = "#ebcb8b", name = "js" },
      jsx = { icon = "", color = "#519aba", name = "jsx" },
      md = { icon = "", color = "#898998", name = "dm" },
      py = { icon = "", color = "#61afef", name = "py" },
      sh = { icon = "", color = "#6d9086", name = "sh" },
      sql = { icon = "󱘲", color = "#ff75a0", name = "sql" },
      ts = { icon = "", color = "#519aba", name = "ts" },
      tsx = { icon = "", color = "#519aba", name = "ts" },
      toml = { icon = "", color = "#61afef", name = "toml" },
      jpg = { icon = "", color = "#bd77dc", name = "jpg" },
      jpeg = { icon = "", color = "#bd77dc", name = "jpeg" },
      key = { icon = "", color = "#7a0d21", name = "key" },
      pdf = { icon = "", color = "#e8274b", name = "pdf" },
      pem = { icon = "", color = "#e8274b", name = "pem" },
      png = { icon = "", color = "#bd77dc", name = "png" },
      svg = { icon = "", color = "#ffb13b", name = "svg" },
      ttf = { icon = "", color = "#ff75a0", name = "truetypefont" },
      yaml = { icon = "", color = "#ebcb8b", name = "yaml" },
      yml = { icon = "", color = "#ebcb8b", name = "yml" },
      webp = { icon = "", color = "#a1b7ee", name = "webp" },
      [".gitignore"] = { icon = "", color = "#6d8086", name = "GitIgnore" },
      ["robots.txt"] = { icon = "󰚩", color = "#74ba4b", name = "robots" },
      ["package.json"] = { icon = "", color = "#e8274b", name = "PackageJson" },
      ["package-lock.json"] = { icon = "", color = "#7a0d21", name = "PackageLockJson" },
      ["docker-compose.yml"] = { icon = "󰡨", color = "#f55385", name = "DockerCompose" },
      ["docker-compose.yaml"] = { icon = "󰡨", color = "#f55385", name = "DockerCompose" },
    },
    config = function(_, opts)
      require("nvim-web-devicons").set_icon(opts)
    end,
  },
}
